### PR TITLE
Hide overlays if present when changing options in runtime

### PR DESCRIPTION
**Pull request by itaybre**
## Changes
- Added buttons on the Demo app to toggle options:
Simulator Screen Shot - iPhone 13 - 2022-05-12 at 22 08 10

- Make sure to hide all active overlays when toggling options

### CODE REVIEW

**Comment by itaybre** [comment]
@jtrivedi did you had time to check the PR?

**Comment by jtrivedi** [comment]
Hey there, sorry for the delay. This patch includes some UI work, which I don't think is relevant to this issue. If you'd like to update the patch to just hide the overlays if needed, I'm happy to review it.

**Comment by itaybre** [comment]
@jtrivedi reverted the changes
I wanted to add an UI to easily test the change + make it easier to understand how TouchInspector works for new users

**Comment by jtrivedi** [comment]
Thank you!

**Pull request merged**
